live_config_reload = true

[env]
TERM = 'xterm-256color'

[font]
size = 18.0

[font.normal]
family = "MonoLisa Nerd Font"
style = "Regular"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.85

[window.padding]
x = 18
y = 5

